# Tutorial in NumPy

Inspired from https://github.com/rougier/numpy-100

In [2]:
import numpy as np

In [6]:
#### 3. Create a null vector of size 10 (★☆☆)
null_v = np.zeros(10)
assert len(null_v) == 10
print(null_v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
#### 4. How to find the memory size of any array (★☆☆)
null_v.size

10

In [12]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [13]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
v = np.zeros(10)
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
v = np.arange(10, 50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)
v_rev = np.flip(v)
v_rev

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [29]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
m = np.arange(0, 9).reshape((3, 3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
arr = [1,2,0,0,4,0]
arr_np = np.array(arr, dtype='float32')
idx = np.where(arr_np != 0)
idx

(array([0, 1, 4]),)

In [34]:
#### 11. Create a 3x3 identity matrix (★☆☆)
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#### 12. Create a 3x3x3 array with random values (★☆☆)
np.random.rand(3,3,3)

array([[[0.40680247, 0.46178279, 0.28739544],
        [0.83695881, 0.76492183, 0.4942928 ],
        [0.73151401, 0.01634524, 0.17089584]],

       [[0.18485204, 0.61290863, 0.38850045],
        [0.07063391, 0.61253342, 0.76511871],
        [0.85581327, 0.41137579, 0.11140305]],

       [[0.19930722, 0.69511144, 0.97422226],
        [0.25030982, 0.23858425, 0.55814124],
        [0.53014991, 0.31538564, 0.85696469]]])

In [38]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
m = np.random.rand(10, 10)
min_m = np.min(m)
max_m = np.max(m)
min_m, max_m

(np.float64(0.062493244698860195), np.float64(0.9978650635301849))

In [43]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
mean_v = np.mean(np.random.rand(30))
mean_v

np.float64(0.47373707072572446)

In [47]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
arr = np.zeros((5, 5))
arr[:, 0] = 1
arr[0, :] = 1
arr[-1, :] = 1
arr[:, -1] = 1
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
arr = np.ones((5, 5))
arr[:, 0] = 0
arr[0, :] = 0
arr[-1, :] = 0
arr[:, -1] = 0
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
#### 17. What is the result of the following expression? (★☆☆)
"""python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
"""
0 * np.nan

nan

In [53]:
np.nan == np.nan

False

In [54]:
np.inf > np.nan

False

In [55]:
np.nan - np.nan

nan

In [56]:
np.nan in set([np.nan])

True

In [57]:
0.3 == 3 * 0.1

False

In [80]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
# k = -1 means the "-1"-th diagonal
# np.arange(1, 5) -> just: array([1, 2, 3, 4])
# np.diag(...) will create the full matrix, based on given diagonal :)
m = np.diag(np.arange(1, 5), k=-1)
m

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [81]:
np.arange(1,5)

array([1, 2, 3, 4])

In [85]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [94]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
mat = np.random.randn(6, 7, 8)
mat
"""
In NumPy, arrays are stored in row-major order (C-style), meaning:

The last axis (z) index changes most rapidly
Then the middle axis (y)
Then the first axis (x)

---------

To manually calculate this:

For a position p, we can find its coordinates (x,y,z) as follows:
z = p % 8  (remainder when divided by 8) --> 8 * {12} = 96 --> 99 - 96 = 3
y = (p // 8) % 7  (remainder when divided by 7 after dividing p by 8) --> {12} - 7 = 5
x = (p // (8*7))  (integer division by total elements in y and z dimensions)


---------

For index 99:

z = 99 % 8 = 3
y = (99 // 8) % 7 = (12) % 7 = 5
x = 99 // (8*7) = 99 // 56 = 1

"""
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


In [5]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
mat = np.tile(np.array([[0, 1], [1, 0]]), (4,4))
mat

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
#### 22. Normalize a 5x5 random matrix (★☆☆)
mat = np.random.rand(5, 5)
mat = (mat - np.mean(mat)) / np.std(mat)
mat

In [12]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [16]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
mat1 = np.random.rand(5,3)
mat2 = np.random.rand(3,2)
mat3 = mat1 @ mat2
mat3

array([[1.15761006, 0.55951658],
       [1.23901748, 0.52734698],
       [0.67998416, 0.27363585],
       [0.90403817, 0.59298378],
       [0.96594806, 0.26159792]])

In [18]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
arr = np.arange(10)
arr[(arr > 2) & (arr < 9)] *= -1
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

In [20]:
#### 26. What is the output of the following script? (★☆☆)
"""
print(sum(range(5),-1))
"""
# 4 + 3 + 2 + 1 + 0 *= -1 -> -9
print(sum(range(5),-1))

9


In [26]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
"""
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
"""
Z = np.arange(12)
Z**Z
2 << Z >> 2
Z <- Z
Z/1/1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [29]:
#### 28. What are the result of the following expressions? (★☆☆)
"""
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
"""

# nan
np.array(0) / np.array(0)
# 0
np.array(0) // np.array(0)
# inf
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_8872/2205693117.py:9: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_8872/2205693117.py:11: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_8872/2205693117.py:13: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [38]:
#### 29. How to round away from zero a float array ? (★☆☆)
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# or
print('\n***\n')
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-9.51253675 -9.93285124 -2.61610147  2.31533896 -1.45289647 -8.53549491
 -6.09128931 -6.41939535  6.42100942  7.08305003]
[-10. -10.  -3.   3.  -2.  -9.  -7.  -7.   7.   8.]

***

[ 6.49208729 -6.54925717  4.46980584 -7.6686344   7.65523331  5.3440749
 -5.46166499 -0.22755488 -8.2502127  -4.25976223]
[ 7. -7.  5. -8.  8.  6. -6. -1. -9. -5.]


In [ ]:
#### 30. How to find common values between two arrays? (★☆☆)
arr1 = [0, 1, 2, 5]
arr_np_1 = np.array(arr1, dtype='float32')
arr2 = [0, 1, 2, 3, 7]
arr_np_2 = np.array(arr2, dtype='float32')

np.intersect1d(arr_np_1, arr_np_2)

array([0., 1., 2.], dtype=float32)