# Tutorial in NumPy

Inspired from https://github.com/rougier/numpy-100

In [1]:
import numpy as np

In [6]:
#### 3. Create a null vector of size 10 (★☆☆)
null_v = np.zeros(10)
assert len(null_v) == 10
print(null_v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
#### 4. How to find the memory size of any array (★☆☆)
null_v.size

10

In [12]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [13]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
v = np.zeros(10)
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
v = np.arange(10, 50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)
v_rev = np.flip(v)
v_rev

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [29]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
m = np.arange(0, 9).reshape((3, 3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
